version: '3.8'
services:
  mysql_db:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_TCP_PORT=${DB_PORT}
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - NODE_ENV=development
    depends_on:
      - mysql_db
    volumes:
      - ./src:/app/src